# Generated by Django 5.2.7 on 2026-07-13 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings_app", "0004_chatchannel_chatmessage_tenancyagreement"),
        ("rooms", "0013_delete_propertyleveldocument_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferencingApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=255, unique=True)),
                ("applicant_name", models.CharField(max_length=255)),
                ("applicant_email", models.EmailField(db_index=True, max_length=254)),
                ("applicant_phone", models.CharField(blank=True, max_length=50)),
                ("application_data", models.JSONField(blank=True, default=dict)),
                ("uploaded_documents", models.JSONField(blank=True, default=list)),
                ("credit_score", models.IntegerField(blank=True, null=True)),
                ("ccj_iva_found", models.BooleanField(default=False)),
                ("missed_payments", models.IntegerField(default=0)),
                ("ai_raw_check_result", models.JSONField(blank=True, default=dict)),
                ("report_pdf_url", models.TextField(blank=True, null=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Decision"),
                            ("approve", "Approve"),
                            ("caution", "Approve with Guarantor"),
                            ("decline", "Decline"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("landlord_override_notes", models.TextField(blank=True, default="")),
                ("tenancy_end_date", models.DateField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("legal_dispute_active", models.BooleanField(default=False)),
                ("is_archived_or_deleted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("submitted", "Submitted"),
                            ("processing", "Processing Checks"),
                            ("completed", "Completed"),
                            ("failed", "Failed Verification"),
                        ],
                        default="invited",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "landlord_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_referencing_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referencing_applications",
                        to="rooms.room",
                    ),
                ),
            ],
        ),
    ]
