# Generated by Django 5.2.7 on 2026-07-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings_app", "0005_referencingapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentpayment",
            name="stripe_checkout_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rentpayment",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
